# Generated by Django 5.0.3 on 2024-03-28 19:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.create_custom_path
            ),
        ),
    ]
